"""empty message

Revision ID: 4291dee0fe48
Revises: ca9427c25fcb
Create Date: 2020-03-01 13:49:55.247414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4291dee0fe48'
down_revision = 'ca9427c25fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
